<?php

declare(strict_types=1);
require_once __DIR__ . '/../../app/bootstrap.php';
Auth::requirePermission('manage_homepage');
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); $slide=$id?HomeManager::slide((int)$id):null; if($id&&!$slide)redirect(adminUrl('homepage/'));
$error=null;
if(isPost()){CSRF::verify($_POST['csrf_token']??null);try{$new=HomeManager::saveSlide($_POST,$id?:null);Auth::audit(Auth::id(),$id?'update':'create','home_hero_slide',$new,($id?'Updated':'Created').' homepage hero slide: '.($_POST['title']??''));flash('success','Hero slide saved.');redirect(adminUrl('homepage/slide.php?id='.$new));}catch(Throwable $e){$error=APP_DEBUG?$e->getMessage():'The hero slide could not be saved.';$slide=array_merge((array)$slide,$_POST);}}
$pageTitle=$slide?'Edit Hero Slide':'Add Hero Slide';$activeNav='homepage';require __DIR__.'/../partials/header.php';require __DIR__.'/../partials/sidebar.php';
?>
<main class="admin-content"><?php $breadcrumbs=[['label'=>'Dashboard','url'=>adminUrl('dashboard.php')],['label'=>'Homepage','url'=>adminUrl('homepage/')],['label'=>$slide?'Edit Hero Slide':'Add Hero Slide','url'=>null]];require __DIR__.'/../partials/breadcrumbs.php';$heading=$slide?'Edit Hero Slide':'Add Hero Slide';$description='Preserve the existing legacy ID for migrated slides.';$actionUrl=adminUrl('homepage/');$actionLabel='Back';require __DIR__.'/../partials/page-heading.php';require __DIR__.'/../partials/alerts.php';?>
<?php if($error):?><div class="alert alert-error"><?=e($error)?></div><?php endif;?><section class="form-card"><form method="post"><?=CSRF::field()?><div class="form-grid"><div class="form-field"><label>Legacy ID</label><input name="legacy_id" value="<?=e($slide['legacy_id']??'')?>" required></div><div class="form-field"><label>Sort order</label><input type="number" min="0" name="sort_order" value="<?=e((string)($slide['sort_order']??0))?>"></div><div class="form-field form-field-wide"><label>Title</label><input name="title" maxlength="255" value="<?=e($slide['title']??'')?>" required></div><div class="form-field form-field-wide"><label>Description</label><textarea name="description" rows="6"><?=e($slide['description']??'')?></textarea></div><div class="form-field form-field-wide"><label>Image path</label><input name="image_path" maxlength="500" value="<?=e($slide['image_path']??'')?>" required></div><div class="form-field form-field-wide"><label>Indicator</label><input name="indicator" value="<?=e($slide['indicator']??'')?>"></div></div><label class="permission-option"><input type="checkbox" name="is_active" value="1" <?=!isset($slide['is_active'])||$slide['is_active']?'checked':''?>><span><strong>Active</strong></span></label><div class="form-actions"><a class="button-link button-secondary" href="<?=e(adminUrl('homepage/'))?>">Cancel</a><button class="button-primary" type="submit">Save Slide</button></div></form></section></main><?php require __DIR__.'/../partials/footer.php'; ?>
