<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>@yield('title', 'State Corps')</title>
<link rel="icon" href="{{ asset('assets/images/favicon1.png') }}" sizes="32x32">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
<link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/navigation.css') }}">
@stack('head')</head><body>
<header class="header"><div class="header-inner"><div class="main-navigation"><div class="floating-logo"><a href="{{ route('home') }}" class="logo"><img src="{{ asset('assets/images/logo.png') }}" alt="State Corps" class="logo-img"></a></div><div class="mobile-menu-toggle"><span></span><span></span><span></span></div><div class="nav-rows"><div class="nav-row nav-row-top"><div class="container"><div class="nav-row-inner"><nav class="nav-menu nav-menu-top"><ul class="nav-list nav-list-top"><li class="nav-item-top"><a href="{{ route('contact') }}" class="nav-link-top">Contact Us</a></li></ul></nav></div></div></div><div class="nav-row nav-row-bottom"><div class="container"><div class="nav-row-inner"><nav class="nav-menu nav-menu-bottom"><ul class="nav-list nav-list-bottom"><li class="nav-item"><a href="{{ route('home') }}" class="nav-link"><span class="nav-text">Home</span></a></li><li class="nav-item"><a href="{{ route('projects.index') }}" class="nav-link"><span class="nav-text">Projects</span></a></li><li class="nav-item"><a href="{{ route('admin.dashboard') }}" class="nav-link"><span class="nav-text">Admin</span></a></li></ul></nav></div></div></div></div></div></div></header>
@yield('content')
<footer class="site-footer"><div class="container"><div class="footer-main"><div class="footer-col footer-company"><h2 class="footer-name">State Corps</h2><div class="footer-statement">Building Infrastructure. Empowering Communities. Driving Sustainable Growth.</div></div><div class="footer-col"><h4>Projects</h4><ul><li><a href="{{ route('projects.index') }}">All Projects</a></li></ul></div><div class="footer-col"><h4>Contact</h4><ul class="footer-contact"><li>comms@statecorps.com</li></ul></div></div><div class="footer-bottom"><div class="footer-copyright">© {{ now()->year }} State Corps. All Rights Reserved.</div></div></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script><script src="{{ asset('assets/js/main.js') }}" defer></script>@stack('scripts')</body></html>
