<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/bootstrap.php';require_once __DIR__ . '/../../app/core/MediaLibraryManager.php';
Auth::requirePermission('manage_assets');$id=(int)($_GET['id']??0);$row=MediaLibraryManager::find($id);if(!$row){http_response_code(404);exit('Asset not found.');}$error=null;$references=MediaLibraryManager::references((string)$row['relative_path']);
if($_SERVER['REQUEST_METHOD']==='POST'){try{CSRF::check($_POST['_csrf']??'');$action=(string)($_POST['action']??'');if($action==='save'){MediaLibraryManager::updateMeta($id,(string)($_POST['display_name']??''),(string)($_POST['alt_text']??''),(string)($_POST['category']??''),(string)($_POST['status']??'active'));Auth::audit(Auth::id(),'update','asset',$id,'Updated asset metadata.');Session::flash('success','Asset details updated.');redirect(adminUrl('assets-library/edit.php?id='.$id));}if($action==='rename'){MediaLibraryManager::rename($id,(string)($_POST['new_name']??''));Auth::audit(Auth::id(),'update','asset',$id,'Renamed asset file.');Session::flash('success','Asset renamed and live database references were updated.');redirect(adminUrl('assets-library/edit.php?id='.$id));}if($action==='delete'){MediaLibraryManager::delete($id);Auth::audit(Auth::id(),'delete','asset',$id,'Deleted asset.');Session::flash('success','Asset deleted.');redirect(adminUrl('assets-library/'));}}catch(Throwable $e){$error=APP_DEBUG?$e->getMessage():'The requested asset operation failed.';}}
$pageTitle='Edit Asset';require __DIR__.'/../partials/header.php';require __DIR__.'/../partials/sidebar.php';
?><main class="admin-main"><div class="admin-container"><div class="media-library-hero"><div><h1>Edit Asset</h1><p><?=e($row['original_name'])?></p></div><a class="btn btn-secondary" href="<?=e(adminUrl('assets-library/'))?>">Back</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="admin-card media-detail"><div class="media-detail-preview"><?php if(str_starts_with((string)$row['mime_type'],'image/')):?><img src="<?=e(function_exists('baseUrl')?baseUrl($row['relative_path']):$row['relative_path'])?>" alt="<?=e((string)($row['alt_text']??''))?>"><?php else:?><div class="media-library-file-large"><?=e(strtoupper(pathinfo($row['original_name'],PATHINFO_EXTENSION)?:'FILE'))?></div><?php endif;?></div><div><div class="muted">Path</div><code><?=e($row['relative_path'])?></code><div class="muted" style="margin-top:.55rem">References</div><strong><?=e((string)count($references))?></strong><div class="muted"><?=count($references)?'Live database reference(s) detected.':'No live database references detected.'?></div></div></div>
<div class="admin-card"><h2>Library details</h2><form method="post"><input type="hidden" name="_csrf" value="<?=e(CSRF::token())?>"><input type="hidden" name="action" value="save"><label>Library name<input class="form-control" name="display_name" value="<?=e(pathinfo($row['original_name'],PATHINFO_FILENAME))?>" maxlength="150"></label><label>Category<input class="form-control" name="category" value="<?=e((string)($row['category']??''))?>" maxlength="80"></label><label>Status<select class="form-control" name="status"><option value="active" <?=($row['status']??'active')==='active'?'selected':''?>>Active</option><option value="archived" <?=($row['status']??'active')==='archived'?'selected':''?>>Archived</option></select></label><label>Alt text<textarea class="form-control" name="alt_text" maxlength="500" rows="3"><?=e((string)($row['alt_text']??''))?></textarea></label><button class="btn btn-primary" type="submit">Save Details</button></form></div>
<div class="admin-card"><h2>Rename physical file</h2><p class="muted">Renaming updates the stored file path and replaces that path in live CMS database text fields so existing pages keep working.</p><form method="post"><input type="hidden" name="_csrf" value="<?=e(CSRF::token())?>"><input type="hidden" name="action" value="rename"><div class="media-picker-row"><input class="form-control" name="new_name" value="<?=e(pathinfo($row['original_name'],PATHINFO_FILENAME))?>" maxlength="150"><button class="btn btn-primary" type="submit">Rename File</button></div></form></div>
<div class="admin-card"><h2>Live references</h2><?php if($references):?><div class="table-responsive"><table class="admin-table"><thead><tr><th>Table</th><th>Column</th><th>Row ID</th></tr></thead><tbody><?php foreach($references as $ref):?><tr><td><code><?=e($ref['table_name'])?></code></td><td><code><?=e($ref['column_name'])?></code></td><td><?=e((string)$ref['row_id'])?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><p>No live references.</p><?php endif;?></div>
<div class="admin-card"><form method="post" onsubmit="return confirm('Delete this asset permanently?');"><input type="hidden" name="_csrf" value="<?=e(CSRF::token())?>"><input type="hidden" name="action" value="delete"><button class="btn btn-danger" type="submit" <?= $references ? 'disabled title="Remove live references first"' : '' ?>>Delete Asset</button></form></div></div></main><?php require __DIR__.'/../partials/footer.php';?>
